// Code generated by Spice. DO NOT EDIT.
// Source: examples/commerce/notifications/notifications.go:62
// Source: examples/commerce/notifications/notifications.go:80
//go:build !spice_generate

package notifications

import (
	mail "github.com/StevenBuglione/spice/mail"
)

// spiceImplements4fd59814b0aa verifies the explicit @Implements binding for spice:symbol:v1|type|63:github.com/StevenBuglione/spice/examples/commerce/notifications|0:|11:SystemClock.
var spiceImplements4fd59814b0aa Clock = *new(*SystemClock)

// spiceImplements262d0dc416a4 verifies the explicit @Implements binding for spice:symbol:v1|type|63:github.com/StevenBuglione/spice/examples/commerce/notifications|0:|8:Delivery.
var spiceImplements262d0dc416a4 mail.Sender = *new(*Delivery)
