//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: payments/payments.go:26
// Source: payments/payments.go:49
// Source: payments/payments.go:63

package spicegen

import (
	fmt "fmt"

	spiceconfig "github.com/spice-framework/spice/config"
	payments "github.com/spice-framework/spice/examples/commerce/payments"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructOfflineProcessor_713bc812 performs the direct construction selected for bean "offlineProcessor".
// Spice source identity: spice:symbol:v1|type|59:github.com/spice-framework/spice/examples/commerce/payments|0:|16:OfflineProcessor.
func ConstructOfflineProcessor_713bc812() (*payments.OfflineProcessor, spicelifecycle.Cleanup, error) {
	return new(payments.OfflineProcessor), nil, nil
}

// spiceImplementsOfflineProcessorAsProcessor_629317a7 identifies the explicit @Implements binding for spice:symbol:v1|type|59:github.com/spice-framework/spice/examples/commerce/payments|0:|16:OfflineProcessor.
var _ payments.Processor = (*payments.OfflineProcessor)(nil)

// ConstructStripeProcessor_dfa08a08 performs the direct construction selected for bean "stripeProcessor".
// Spice source identity: spice:symbol:v1|type|59:github.com/spice-framework/spice/examples/commerce/payments|0:|7:Service.
func ConstructStripeProcessor_dfa08a08(dependency0 payments.Settings) (*payments.Service, spicelifecycle.Cleanup, error) {
	value, err := payments.NewService(dependency0)
	if err != nil {
		var zero *payments.Service
		return zero, nil, fmt.Errorf("construct bean stripeProcessor (*github.com/spice-framework/spice/examples/commerce/payments.Service, source spice:symbol:v1|type|59:github.com/spice-framework/spice/examples/commerce/payments|0:|7:Service): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsStripeProcessorAsProcessor_678a04c2 identifies the explicit @Implements binding for spice:symbol:v1|type|59:github.com/spice-framework/spice/examples/commerce/payments|0:|7:Service.
var _ payments.Processor = (*payments.Service)(nil)

// BindSettings_20c0dec1 binds the validated configuration declared by spice:symbol:v1|type|59:github.com/spice-framework/spice/examples/commerce/payments|0:|8:Settings.
func BindSettings_20c0dec1(configurationSnapshot spiceconfig.Snapshot) (payments.Settings, error) {
	value := payments.Settings{}
	if _, configured := configurationSnapshot.Lookup("commerce.payments.maximum-cents"); configured {
		rawValue, valueErr := configurationSnapshot.Integer("commerce.payments.maximum-cents")
		if valueErr != nil {
			return payments.Settings{}, fmt.Errorf("decode configuration property commerce.payments.maximum-cents for github.com/spice-framework/spice/examples/commerce/payments.Settings.MaximumCents: %w", valueErr)
		}
		convertedValue := int(rawValue)
		if int64(convertedValue) != rawValue {
			return payments.Settings{}, fmt.Errorf("decode configuration property commerce.payments.maximum-cents for github.com/spice-framework/spice/examples/commerce/payments.Settings.MaximumCents: value is outside int")
		}
		value.MaximumCents = convertedValue
	}
	return value, nil
}
