//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: payments/payments.go:26
// Source: payments/payments.go:49
// Source: payments/payments.go:63

package spicegen

import (
	fmt "fmt"

	payments "github.com/spice-framework/commerce/payments"
	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructOfflineProcessor_cef093bf performs the direct construction selected for bean "offlineProcessor".
// Spice source identity: spice:symbol:v1|type|44:github.com/spice-framework/commerce/payments|0:|16:OfflineProcessor.
func ConstructOfflineProcessor_cef093bf() (*payments.OfflineProcessor, spicelifecycle.Cleanup, error) {
	return new(payments.OfflineProcessor), nil, nil
}

// spiceImplementsOfflineProcessorAsProcessor_ac5ba89f identifies the explicit @Implements binding for spice:symbol:v1|type|44:github.com/spice-framework/commerce/payments|0:|16:OfflineProcessor.
var _ payments.Processor = (*payments.OfflineProcessor)(nil)

// ConstructStripeProcessor_7def5e1d performs the direct construction selected for bean "stripeProcessor".
// Spice source identity: spice:symbol:v1|type|44:github.com/spice-framework/commerce/payments|0:|7:Service.
func ConstructStripeProcessor_7def5e1d(dependency0 payments.Settings) (*payments.Service, spicelifecycle.Cleanup, error) {
	value, err := payments.NewService(dependency0)
	if err != nil {
		var zero *payments.Service
		return zero, nil, fmt.Errorf("construct bean stripeProcessor (*github.com/spice-framework/commerce/payments.Service, source spice:symbol:v1|type|44:github.com/spice-framework/commerce/payments|0:|7:Service): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsStripeProcessorAsProcessor_ab8defeb identifies the explicit @Implements binding for spice:symbol:v1|type|44:github.com/spice-framework/commerce/payments|0:|7:Service.
var _ payments.Processor = (*payments.Service)(nil)

// BindSettings_71d9f317 binds the validated configuration declared by spice:symbol:v1|type|44:github.com/spice-framework/commerce/payments|0:|8:Settings.
func BindSettings_71d9f317(configurationSnapshot spiceconfig.Snapshot) (payments.Settings, error) {
	value := payments.Settings{}
	if _, configured := configurationSnapshot.Lookup("commerce.payments.maximum-cents"); configured {
		rawValue, valueErr := configurationSnapshot.Integer("commerce.payments.maximum-cents")
		if valueErr != nil {
			return payments.Settings{}, fmt.Errorf("decode configuration property commerce.payments.maximum-cents for github.com/spice-framework/commerce/payments.Settings.MaximumCents: %w", valueErr)
		}
		convertedValue := int(rawValue)
		if int64(convertedValue) != rawValue {
			return payments.Settings{}, fmt.Errorf("decode configuration property commerce.payments.maximum-cents for github.com/spice-framework/commerce/payments.Settings.MaximumCents: value is outside int")
		}
		value.MaximumCents = convertedValue
	}
	return value, nil
}
