//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// This bridge intentionally contains no application wiring.

package main

import spicegen "github.com/StevenBuglione/spice/internal/spicegen/commerce"

const (
	TargetID    = spicegen.TargetID
	ExitSuccess = spicegen.ExitSuccess
	ExitFailure = spicegen.ExitFailure
	ExitUsage   = spicegen.ExitUsage
)

type (
	Application            = spicegen.Application
	ApplicationOptions     = spicegen.ApplicationOptions
	Components             = spicegen.Components
	CommandOptions         = spicegen.CommandOptions
	ShutdownContextFactory = spicegen.ShutdownContextFactory
)

var (
	ConfigurationSchema       = spicegen.ConfigurationSchema
	NewApplication            = spicegen.NewApplication
	NewApplicationWithOptions = spicegen.NewApplicationWithOptions
	RunCommand                = spicegen.RunCommand
)

func spiceMain(arguments []string) int {
	return spicegen.Main(arguments)
}
