//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: examples/commerce/payments/payments.go:49
// Source: examples/commerce/payments/payments.go:63

package payments

// spiceImplements078acc783dcb verifies the explicit @Implements binding for spice:symbol:v1|type|58:github.com/StevenBuglione/spice/examples/commerce/payments|0:|16:OfflineProcessor.
var spiceImplements078acc783dcb Processor = *new(*OfflineProcessor)

// spiceImplementsbd2b3941a8d6 verifies the explicit @Implements binding for spice:symbol:v1|type|58:github.com/StevenBuglione/spice/examples/commerce/payments|0:|7:Service.
var spiceImplementsbd2b3941a8d6 Processor = *new(*Service)
