//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: orders/events.go:29

package spicegen

import (
	orders "github.com/spice-framework/spice/examples/commerce/orders"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructViewAudit_87ee915f performs the direct construction selected for bean "newViewAudit".
// Spice source identity: spice:symbol:v1|function|57:github.com/spice-framework/spice/examples/commerce/orders|0:|12:NewViewAudit.
func ConstructViewAudit_87ee915f() (*orders.ViewAudit, spicelifecycle.Cleanup, error) {
	value := orders.NewViewAudit()
	return value, nil, nil
}
