//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: orders/events.go:29

package spicegen

import (
	orders "github.com/spice-framework/commerce/orders"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructViewAudit_170cdfbe performs the direct construction selected for bean "newViewAudit".
// Spice source identity: spice:symbol:v1|function|42:github.com/spice-framework/commerce/orders|0:|12:NewViewAudit.
func ConstructViewAudit_170cdfbe() (*orders.ViewAudit, spicelifecycle.Cleanup, error) {
	value := orders.NewViewAudit()
	return value, nil, nil
}
