//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: orders/orders.go:32
// Source: orders/orders.go:66

package spicegen

import (
	fmt "fmt"

	spiceconfig "github.com/spice-framework/spice/config"
	data "github.com/spice-framework/spice/data"
	event "github.com/spice-framework/spice/event"
	inventory "github.com/spice-framework/spice/examples/commerce/inventory"
	orders "github.com/spice-framework/spice/examples/commerce/orders"
	payments "github.com/spice-framework/spice/examples/commerce/payments"
	storage "github.com/spice-framework/spice/examples/commerce/storage"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructService_635293ed performs the direct construction selected for bean "newService".
// Spice source identity: spice:symbol:v1|function|57:github.com/spice-framework/spice/examples/commerce/orders|0:|10:NewService.
func ConstructService_635293ed(dependency0 orders.Settings, dependency1 *inventory.Service, dependency2 payments.Processor, dependency3 event.Publisher[orders.OrderViewed], dependency4 storage.Orders, dependency5 data.Executor) (*orders.Service, spicelifecycle.Cleanup, error) {
	value, err := orders.NewService(dependency0, dependency1, dependency2, dependency3, dependency4, dependency5)
	if err != nil {
		var zero *orders.Service
		return zero, nil, fmt.Errorf("construct bean newService (*github.com/spice-framework/spice/examples/commerce/orders.Service, source spice:symbol:v1|function|57:github.com/spice-framework/spice/examples/commerce/orders|0:|10:NewService): %w", err)
	}
	return value, nil, nil
}

// BindSettings_f28e33eb binds the validated configuration declared by spice:symbol:v1|type|57:github.com/spice-framework/spice/examples/commerce/orders|0:|8:Settings.
func BindSettings_f28e33eb(configurationSnapshot spiceconfig.Snapshot) (orders.Settings, error) {
	value := orders.Settings{}
	if _, configured := configurationSnapshot.Lookup("commerce.orders.sku"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("commerce.orders.sku")
		if valueErr != nil {
			return orders.Settings{}, fmt.Errorf("decode configuration property commerce.orders.sku for github.com/spice-framework/spice/examples/commerce/orders.Settings.SKU: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.SKU = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("commerce.orders.unit-price-cents"); configured {
		rawValue, valueErr := configurationSnapshot.Integer("commerce.orders.unit-price-cents")
		if valueErr != nil {
			return orders.Settings{}, fmt.Errorf("decode configuration property commerce.orders.unit-price-cents for github.com/spice-framework/spice/examples/commerce/orders.Settings.UnitPriceCents: %w", valueErr)
		}
		convertedValue := int(rawValue)
		if int64(convertedValue) != rawValue {
			return orders.Settings{}, fmt.Errorf("decode configuration property commerce.orders.unit-price-cents for github.com/spice-framework/spice/examples/commerce/orders.Settings.UnitPriceCents: value is outside int")
		}
		value.UnitPriceCents = convertedValue
	}
	return value, nil
}
