//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: storage/storage.go:66
// Source: storage/storage.go:96
// Source: storage/storage.go:187
// Source: storage/storage.go:197
// Source: storage/storage.go:205
// Source: storage/storage.go:212

package spicegen

import (
	sql "database/sql"
	fmt "fmt"

	storage "github.com/spice-framework/commerce/storage"
	spiceconfig "github.com/spice-framework/spice/config"
	data "github.com/spice-framework/spice/data"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructOpenDatabase_38018081 performs the direct construction selected for bean "openDatabase".
// Spice source identity: spice:symbol:v1|function|43:github.com/spice-framework/commerce/storage|0:|12:OpenDatabase.
func ConstructOpenDatabase_38018081(dependency0 storage.Settings) (*storage.Database, spicelifecycle.Cleanup, error) {
	value, cleanup, err := storage.OpenDatabase(dependency0)
	if err != nil {
		var zero *storage.Database
		return zero, nil, fmt.Errorf("construct bean openDatabase (*github.com/spice-framework/commerce/storage.Database, source spice:symbol:v1|function|43:github.com/spice-framework/commerce/storage|0:|12:OpenDatabase): %w", err)
	}
	return value, cleanup, nil
}

// ConstructReadExecutor_2a7951a6 performs the direct construction selected for bean "readExecutor".
// Spice source identity: spice:symbol:v1|function|43:github.com/spice-framework/commerce/storage|0:|12:ReadExecutor.
func ConstructReadExecutor_2a7951a6(dependency0 *sql.DB) (data.Executor, spicelifecycle.Cleanup, error) {
	value := storage.ReadExecutor(dependency0)
	return value, nil, nil
}

// ConstructTransactions_49415491 performs the direct construction selected for bean "transactions".
// Spice source identity: spice:symbol:v1|function|43:github.com/spice-framework/commerce/storage|0:|12:Transactions.
func ConstructTransactions_49415491(dependency0 *sql.DB) (*data.Manager, spicelifecycle.Cleanup, error) {
	value, err := storage.Transactions(dependency0)
	if err != nil {
		var zero *data.Manager
		return zero, nil, fmt.Errorf("construct bean transactions (*github.com/spice-framework/spice/data.Manager, source spice:symbol:v1|function|43:github.com/spice-framework/commerce/storage|0:|12:Transactions): %w", err)
	}
	return value, nil, nil
}

// ConstructNative_d70bbe3b performs the direct construction selected for bean "native".
// Spice source identity: spice:symbol:v1|function|43:github.com/spice-framework/commerce/storage|0:|6:Native.
func ConstructNative_d70bbe3b(dependency0 *storage.Database) (*sql.DB, spicelifecycle.Cleanup, error) {
	value, err := storage.Native(dependency0)
	if err != nil {
		var zero *sql.DB
		return zero, nil, fmt.Errorf("construct bean native (*database/sql.DB, source spice:symbol:v1|function|43:github.com/spice-framework/commerce/storage|0:|6:Native): %w", err)
	}
	return value, nil, nil
}

// ConstructOrderRepository_9323be91 performs the direct construction selected for bean "orderRepository".
// Spice source identity: spice:symbol:v1|type|43:github.com/spice-framework/commerce/storage|0:|15:OrderRepository.
func ConstructOrderRepository_9323be91() (*storage.OrderRepository, spicelifecycle.Cleanup, error) {
	value, err := storage.NewOrderRepository()
	if err != nil {
		var zero *storage.OrderRepository
		return zero, nil, fmt.Errorf("construct bean orderRepository (*github.com/spice-framework/commerce/storage.OrderRepository, source spice:symbol:v1|type|43:github.com/spice-framework/commerce/storage|0:|15:OrderRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsOrderRepositoryAsOrders_e6020e2f identifies the explicit @Implements binding for spice:symbol:v1|type|43:github.com/spice-framework/commerce/storage|0:|15:OrderRepository.
var _ storage.Orders = (*storage.OrderRepository)(nil)

// BindSettings_50bc017d binds the validated configuration declared by spice:symbol:v1|type|43:github.com/spice-framework/commerce/storage|0:|8:Settings.
func BindSettings_50bc017d(configurationSnapshot spiceconfig.Snapshot) (storage.Settings, error) {
	value := storage.Settings{}
	if _, configured := configurationSnapshot.Lookup("commerce.database.url"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("commerce.database.url")
		if valueErr != nil {
			return storage.Settings{}, fmt.Errorf("decode configuration property commerce.database.url for github.com/spice-framework/commerce/storage.Settings.URL: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.URL = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("commerce.database.allow-insecure"); configured {
		rawValue, valueErr := configurationSnapshot.Boolean("commerce.database.allow-insecure")
		if valueErr != nil {
			return storage.Settings{}, fmt.Errorf("decode configuration property commerce.database.allow-insecure for github.com/spice-framework/commerce/storage.Settings.AllowInsecure: %w", valueErr)
		}
		convertedValue := bool(rawValue)
		value.AllowInsecure = convertedValue
	}
	return value, nil
}
