// Code generated by Spice. DO NOT EDIT.
// Source: examples/commerce/storage/storage.go:212
//go:build !spice_generate

package storage

// spiceImplementsfe640233700d verifies the explicit @Implements binding for spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/commerce/storage|0:|15:OrderRepository.
var spiceImplementsfe640233700d Orders = *new(*OrderRepository)
