//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: main.go:19

package spicegen

// ApplicationTargetCommerce_16450fb1 identifies the generated target selected by spice:symbol:v1|function|50:github.com/spice-framework/spice/examples/commerce|0:|4:main.
const ApplicationTargetCommerce_16450fb1 = "commerce"
