//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: main.go:19

package spicegen

// ApplicationTargetCommerce_f6b95006 identifies the generated target selected by spice:symbol:v1|function|35:github.com/spice-framework/commerce|0:|4:main.
const ApplicationTargetCommerce_f6b95006 = "commerce"
