//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: inventory/inventory.go:28
// Source: inventory/inventory.go:42

package spicegen

import (
	fmt "fmt"

	spiceconfig "github.com/spice-framework/spice/config"
	inventory "github.com/spice-framework/spice/examples/commerce/inventory"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructService_79951d75 performs the direct construction selected for bean "newService".
// Spice source identity: spice:symbol:v1|function|60:github.com/spice-framework/spice/examples/commerce/inventory|0:|10:NewService.
func ConstructService_79951d75(dependency0 inventory.Settings) (*inventory.Service, spicelifecycle.Cleanup, error) {
	value, err := inventory.NewService(dependency0)
	if err != nil {
		var zero *inventory.Service
		return zero, nil, fmt.Errorf("construct bean newService (*github.com/spice-framework/spice/examples/commerce/inventory.Service, source spice:symbol:v1|function|60:github.com/spice-framework/spice/examples/commerce/inventory|0:|10:NewService): %w", err)
	}
	return value, nil, nil
}

// BindSettings_224b83e8 binds the validated configuration declared by spice:symbol:v1|type|60:github.com/spice-framework/spice/examples/commerce/inventory|0:|8:Settings.
func BindSettings_224b83e8(configurationSnapshot spiceconfig.Snapshot) (inventory.Settings, error) {
	value := inventory.Settings{}
	if _, configured := configurationSnapshot.Lookup("commerce.inventory.sku"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("commerce.inventory.sku")
		if valueErr != nil {
			return inventory.Settings{}, fmt.Errorf("decode configuration property commerce.inventory.sku for github.com/spice-framework/spice/examples/commerce/inventory.Settings.SKU: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.SKU = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("commerce.inventory.initial-stock"); configured {
		rawValue, valueErr := configurationSnapshot.Integer("commerce.inventory.initial-stock")
		if valueErr != nil {
			return inventory.Settings{}, fmt.Errorf("decode configuration property commerce.inventory.initial-stock for github.com/spice-framework/spice/examples/commerce/inventory.Settings.InitialStock: %w", valueErr)
		}
		convertedValue := int(rawValue)
		if int64(convertedValue) != rawValue {
			return inventory.Settings{}, fmt.Errorf("decode configuration property commerce.inventory.initial-stock for github.com/spice-framework/spice/examples/commerce/inventory.Settings.InitialStock: value is outside int")
		}
		value.InitialStock = convertedValue
	}
	return value, nil
}
